//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

/**
 * Helper class for marshaling/unmarshaling colors.
 **/
public final class colorsHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, RGB[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                RGB.ice_write(ostr, v[i0]);
            }
        }
    }

    public static RGB[] read(com.zeroc.Ice.InputStream istr)
    {
        final RGB[] v;
        final int len0 = istr.readAndCheckSeqSize(6);
        v = new RGB[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = RGB.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<RGB[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, RGB[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            final int optSize = v == null ? 0 : v.length;
            ostr.writeSize(optSize > 254 ? optSize * 6 + 5 : optSize * 6 + 1);
            colorsHelper.write(ostr, v);
        }
    }

    public static java.util.Optional<RGB[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            RGB[] v;
            v = colorsHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
