//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class Hours implements java.lang.Cloneable,
                              java.io.Serializable
{
    public short fromHour;

    public short toHour;

    public Hours()
    {
    }

    public Hours(short fromHour, short toHour)
    {
        this.fromHour = fromHour;
        this.toHour = toHour;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Hours r = null;
        if(rhs instanceof Hours)
        {
            r = (Hours)rhs;
        }

        if(r != null)
        {
            if(this.fromHour != r.fromHour)
            {
                return false;
            }
            if(this.toHour != r.toHour)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::SmartHome::Hours");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, fromHour);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, toHour);
        return h_;
    }

    public Hours clone()
    {
        Hours c = null;
        try
        {
            c = (Hours)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeShort(this.fromHour);
        ostr.writeShort(this.toHour);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.fromHour = istr.readShort();
        this.toHour = istr.readShort();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Hours v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Hours ice_read(com.zeroc.Ice.InputStream istr)
    {
        Hours v = new Hours();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Hours> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Hours v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(4);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<Hours> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(Hours.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Hours _nullMarshalValue = new Hours();

    /** @hidden */
    public static final long serialVersionUID = 172069155L;
}
