//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public class InvalidDegreeValue extends com.zeroc.Ice.UserException
{
    public InvalidDegreeValue()
    {
        this.data = "Degrees out of range.";
    }

    public InvalidDegreeValue(Throwable cause)
    {
        super(cause);
        this.data = "Degrees out of range.";
    }

    public InvalidDegreeValue(String data)
    {
        this.data = data;
    }

    public InvalidDegreeValue(String data, Throwable cause)
    {
        super(cause);
        this.data = data;
    }

    public String ice_id()
    {
        return "::SmartHome::InvalidDegreeValue";
    }

    public String data;

    /** @hidden */
    @Override
    protected void _writeImpl(com.zeroc.Ice.OutputStream ostr_)
    {
        ostr_.startSlice("::SmartHome::InvalidDegreeValue", -1, true);
        ostr_.writeString(data);
        ostr_.endSlice();
    }

    /** @hidden */
    @Override
    protected void _readImpl(com.zeroc.Ice.InputStream istr_)
    {
        istr_.startSlice();
        data = istr_.readString();
        istr_.endSlice();
    }

    /** @hidden */
    public static final long serialVersionUID = -173082460L;
}
