//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public interface LampWithWorkSchedulePrx extends LampPrx
{
    default java.util.Map<Day, Hours> getPlan()
        throws PowerStatusError
    {
        return getPlan(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default java.util.Map<Day, Hours> getPlan(java.util.Map<String, String> context)
        throws PowerStatusError
    {
        try
        {
            return _iceI_getPlanAsync(context, true).waitForResponseOrUserEx();
        }
        catch(PowerStatusError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<Day, Hours>> getPlanAsync()
    {
        return _iceI_getPlanAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.util.Map<Day, Hours>> getPlanAsync(java.util.Map<String, String> context)
    {
        return _iceI_getPlanAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.util.Map<Day, Hours>> _iceI_getPlanAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.util.Map<Day, Hours>> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPlan", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getPlan);
        f.invoke(true, context, null, null, istr -> {
                     java.util.Map<Day, Hours> ret;
                     ret = planHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getPlan =
    {
        PowerStatusError.class
    };

    default Hours getDayHours(Day day)
        throws PowerStatusError
    {
        return getDayHours(day, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default Hours getDayHours(Day day, java.util.Map<String, String> context)
        throws PowerStatusError
    {
        try
        {
            return _iceI_getDayHoursAsync(day, context, true).waitForResponseOrUserEx();
        }
        catch(PowerStatusError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Hours> getDayHoursAsync(Day day)
    {
        return _iceI_getDayHoursAsync(day, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Hours> getDayHoursAsync(Day day, java.util.Map<String, String> context)
    {
        return _iceI_getDayHoursAsync(day, context, false);
    }

    /**
     * @hidden
     * @param iceP_day -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Hours> _iceI_getDayHoursAsync(Day iceP_day, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Hours> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getDayHours", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getDayHours);
        f.invoke(true, context, null, ostr -> {
                     Day.ice_write(ostr, iceP_day);
                 }, istr -> {
                     Hours ret;
                     ret = Hours.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getDayHours =
    {
        PowerStatusError.class
    };

    default void updateDayHours(Day day, Hours hours)
        throws InvalidHoursError,
               PowerStatusError
    {
        updateDayHours(day, hours, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void updateDayHours(Day day, Hours hours, java.util.Map<String, String> context)
        throws InvalidHoursError,
               PowerStatusError
    {
        try
        {
            _iceI_updateDayHoursAsync(day, hours, context, true).waitForResponseOrUserEx();
        }
        catch(InvalidHoursError ex)
        {
            throw ex;
        }
        catch(PowerStatusError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> updateDayHoursAsync(Day day, Hours hours)
    {
        return _iceI_updateDayHoursAsync(day, hours, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> updateDayHoursAsync(Day day, Hours hours, java.util.Map<String, String> context)
    {
        return _iceI_updateDayHoursAsync(day, hours, context, false);
    }

    /**
     * @hidden
     * @param iceP_day -
     * @param iceP_hours -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_updateDayHoursAsync(Day iceP_day, Hours iceP_hours, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "updateDayHours", null, sync, _iceE_updateDayHours);
        f.invoke(true, context, null, ostr -> {
                     Day.ice_write(ostr, iceP_day);
                     Hours.ice_write(ostr, iceP_hours);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_updateDayHours =
    {
        InvalidHoursError.class,
        PowerStatusError.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static LampWithWorkSchedulePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), LampWithWorkSchedulePrx.class, _LampWithWorkSchedulePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static LampWithWorkSchedulePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), LampWithWorkSchedulePrx.class, _LampWithWorkSchedulePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static LampWithWorkSchedulePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), LampWithWorkSchedulePrx.class, _LampWithWorkSchedulePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static LampWithWorkSchedulePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), LampWithWorkSchedulePrx.class, _LampWithWorkSchedulePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static LampWithWorkSchedulePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, LampWithWorkSchedulePrx.class, _LampWithWorkSchedulePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static LampWithWorkSchedulePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, LampWithWorkSchedulePrx.class, _LampWithWorkSchedulePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (LampWithWorkSchedulePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_adapterId(String newAdapterId)
    {
        return (LampWithWorkSchedulePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (LampWithWorkSchedulePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (LampWithWorkSchedulePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_invocationTimeout(int newTimeout)
    {
        return (LampWithWorkSchedulePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_connectionCached(boolean newCache)
    {
        return (LampWithWorkSchedulePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (LampWithWorkSchedulePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_secure(boolean b)
    {
        return (LampWithWorkSchedulePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (LampWithWorkSchedulePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_preferSecure(boolean b)
    {
        return (LampWithWorkSchedulePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (LampWithWorkSchedulePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (LampWithWorkSchedulePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_collocationOptimized(boolean b)
    {
        return (LampWithWorkSchedulePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_twoway()
    {
        return (LampWithWorkSchedulePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_oneway()
    {
        return (LampWithWorkSchedulePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_batchOneway()
    {
        return (LampWithWorkSchedulePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_datagram()
    {
        return (LampWithWorkSchedulePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_batchDatagram()
    {
        return (LampWithWorkSchedulePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_compress(boolean co)
    {
        return (LampWithWorkSchedulePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_timeout(int t)
    {
        return (LampWithWorkSchedulePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_connectionId(String connectionId)
    {
        return (LampWithWorkSchedulePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default LampWithWorkSchedulePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (LampWithWorkSchedulePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHome::LampWithWorkSchedule";
    }
}
