//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public interface LampWithWorkSchedule extends Lamp
{
    java.util.Map<Day, Hours> getPlan(com.zeroc.Ice.Current current)
        throws PowerStatusError;

    Hours getDayHours(Day day, com.zeroc.Ice.Current current)
        throws PowerStatusError;

    void updateDayHours(Day day, Hours hours, com.zeroc.Ice.Current current)
        throws InvalidHoursError,
               PowerStatusError;

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Ice::Object",
        "::SmartHome::Lamp",
        "::SmartHome::LampWithWorkSchedule"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::SmartHome::LampWithWorkSchedule";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPlan(LampWithWorkSchedule obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        inS.readEmptyParams();
        java.util.Map<Day, Hours> ret = obj.getPlan(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        planHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getDayHours(LampWithWorkSchedule obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(com.zeroc.Ice.OperationMode.Idempotent, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        Day iceP_day;
        iceP_day = Day.ice_read(istr);
        inS.endReadParams();
        Hours ret = obj.getDayHours(iceP_day, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        Hours.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
     * @throws com.zeroc.Ice.UserException -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_updateDayHours(LampWithWorkSchedule obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        Day iceP_day;
        Hours iceP_hours;
        iceP_day = Day.ice_read(istr);
        iceP_hours = Hours.ice_read(istr);
        inS.endReadParams();
        obj.updateDayHours(iceP_day, iceP_hours, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "getBrightnessPercentage",
        "getDayHours",
        "getPlan",
        "getStatus",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "setBrightnessPercentage",
        "setPowerStatus",
        "updateDayHours"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return Lamp._iceD_getBrightnessPercentage(this, in, current);
            }
            case 1:
            {
                return _iceD_getDayHours(this, in, current);
            }
            case 2:
            {
                return _iceD_getPlan(this, in, current);
            }
            case 3:
            {
                return Lamp._iceD_getStatus(this, in, current);
            }
            case 4:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 5:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 8:
            {
                return Lamp._iceD_setBrightnessPercentage(this, in, current);
            }
            case 9:
            {
                return Lamp._iceD_setPowerStatus(this, in, current);
            }
            case 10:
            {
                return _iceD_updateDayHours(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
