//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `smarthome.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SmartHome;

public interface LampRGBPrx extends LampPrx
{
    default RGB[] getColorList()
        throws PowerStatusError
    {
        return getColorList(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default RGB[] getColorList(java.util.Map<String, String> context)
        throws PowerStatusError
    {
        try
        {
            return _iceI_getColorListAsync(context, true).waitForResponseOrUserEx();
        }
        catch(PowerStatusError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<RGB[]> getColorListAsync()
    {
        return _iceI_getColorListAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<RGB[]> getColorListAsync(java.util.Map<String, String> context)
    {
        return _iceI_getColorListAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<RGB[]> _iceI_getColorListAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<RGB[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getColorList", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getColorList);
        f.invoke(true, context, null, null, istr -> {
                     RGB[] ret;
                     ret = colorsHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getColorList =
    {
        PowerStatusError.class
    };

    default void addColorToList(RGB color)
        throws PowerStatusError,
               RGBListMaxSizeError,
               RGBValueError
    {
        addColorToList(color, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void addColorToList(RGB color, java.util.Map<String, String> context)
        throws PowerStatusError,
               RGBListMaxSizeError,
               RGBValueError
    {
        try
        {
            _iceI_addColorToListAsync(color, context, true).waitForResponseOrUserEx();
        }
        catch(PowerStatusError ex)
        {
            throw ex;
        }
        catch(RGBListMaxSizeError ex)
        {
            throw ex;
        }
        catch(RGBValueError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> addColorToListAsync(RGB color)
    {
        return _iceI_addColorToListAsync(color, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> addColorToListAsync(RGB color, java.util.Map<String, String> context)
    {
        return _iceI_addColorToListAsync(color, context, false);
    }

    /**
     * @hidden
     * @param iceP_color -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_addColorToListAsync(RGB iceP_color, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "addColorToList", null, sync, _iceE_addColorToList);
        f.invoke(true, context, null, ostr -> {
                     RGB.ice_write(ostr, iceP_color);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_addColorToList =
    {
        PowerStatusError.class,
        RGBListMaxSizeError.class,
        RGBValueError.class
    };

    default void deleteColorFromList(int index)
        throws ListColorsIndexOutOfRange,
               PowerStatusError
    {
        deleteColorFromList(index, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void deleteColorFromList(int index, java.util.Map<String, String> context)
        throws ListColorsIndexOutOfRange,
               PowerStatusError
    {
        try
        {
            _iceI_deleteColorFromListAsync(index, context, true).waitForResponseOrUserEx();
        }
        catch(ListColorsIndexOutOfRange ex)
        {
            throw ex;
        }
        catch(PowerStatusError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<Void> deleteColorFromListAsync(int index)
    {
        return _iceI_deleteColorFromListAsync(index, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> deleteColorFromListAsync(int index, java.util.Map<String, String> context)
    {
        return _iceI_deleteColorFromListAsync(index, context, false);
    }

    /**
     * @hidden
     * @param iceP_index -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_deleteColorFromListAsync(int iceP_index, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "deleteColorFromList", null, sync, _iceE_deleteColorFromList);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_index);
                 }, null);
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_deleteColorFromList =
    {
        ListColorsIndexOutOfRange.class,
        PowerStatusError.class
    };

    default RGB getCurrentColor()
        throws PowerStatusError
    {
        return getCurrentColor(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default RGB getCurrentColor(java.util.Map<String, String> context)
        throws PowerStatusError
    {
        try
        {
            return _iceI_getCurrentColorAsync(context, true).waitForResponseOrUserEx();
        }
        catch(PowerStatusError ex)
        {
            throw ex;
        }
        catch(com.zeroc.Ice.UserException ex)
        {
            throw new com.zeroc.Ice.UnknownUserException(ex.ice_id(), ex);
        }
    }

    default java.util.concurrent.CompletableFuture<RGB> getCurrentColorAsync()
    {
        return _iceI_getCurrentColorAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<RGB> getCurrentColorAsync(java.util.Map<String, String> context)
    {
        return _iceI_getCurrentColorAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<RGB> _iceI_getCurrentColorAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<RGB> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCurrentColor", com.zeroc.Ice.OperationMode.Idempotent, sync, _iceE_getCurrentColor);
        f.invoke(true, context, null, null, istr -> {
                     RGB ret;
                     ret = RGB.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    /** @hidden */
    static final Class<?>[] _iceE_getCurrentColor =
    {
        PowerStatusError.class
    };

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static LampRGBPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), LampRGBPrx.class, _LampRGBPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static LampRGBPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), LampRGBPrx.class, _LampRGBPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static LampRGBPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), LampRGBPrx.class, _LampRGBPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static LampRGBPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), LampRGBPrx.class, _LampRGBPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static LampRGBPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, LampRGBPrx.class, _LampRGBPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static LampRGBPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, LampRGBPrx.class, _LampRGBPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default LampRGBPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (LampRGBPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default LampRGBPrx ice_adapterId(String newAdapterId)
    {
        return (LampRGBPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default LampRGBPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (LampRGBPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default LampRGBPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (LampRGBPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default LampRGBPrx ice_invocationTimeout(int newTimeout)
    {
        return (LampRGBPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default LampRGBPrx ice_connectionCached(boolean newCache)
    {
        return (LampRGBPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default LampRGBPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (LampRGBPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default LampRGBPrx ice_secure(boolean b)
    {
        return (LampRGBPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default LampRGBPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (LampRGBPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default LampRGBPrx ice_preferSecure(boolean b)
    {
        return (LampRGBPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default LampRGBPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (LampRGBPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default LampRGBPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (LampRGBPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default LampRGBPrx ice_collocationOptimized(boolean b)
    {
        return (LampRGBPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default LampRGBPrx ice_twoway()
    {
        return (LampRGBPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default LampRGBPrx ice_oneway()
    {
        return (LampRGBPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default LampRGBPrx ice_batchOneway()
    {
        return (LampRGBPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default LampRGBPrx ice_datagram()
    {
        return (LampRGBPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default LampRGBPrx ice_batchDatagram()
    {
        return (LampRGBPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default LampRGBPrx ice_compress(boolean co)
    {
        return (LampRGBPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default LampRGBPrx ice_timeout(int t)
    {
        return (LampRGBPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default LampRGBPrx ice_connectionId(String connectionId)
    {
        return (LampRGBPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default LampRGBPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (LampRGBPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::SmartHome::LampRGB";
    }
}
